/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import controller.PixController;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author kelly
 */
public class PixFrame extends javax.swing.JFrame {

    private JTextField txtChave;
    private JTextField txtValor;
    private JButton btnEnviar;
    
    private PixController controller;
    
    public PixFrame (PixController controller) {
        
        this.controller = controller;
        
        setTitle("PIX FRAME");
        setSize(350,180);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        
        setLayout(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(10, 10, 5, 10);
        gbc.fill = GridBagConstraints.HORIZONTAL;

        JLabel lblChave = new JLabel("Chave Pix:");
        txtChave = new JTextField(15);

        JLabel lblValor = new JLabel("Valor (R$):");
        txtValor = new JTextField(15);

        btnEnviar = new JButton("Enviar PIX");

        // Linha 0 - Chave
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 0;
        add(lblChave, gbc);

        gbc.gridx = 1;
        gbc.weightx = 1;
        add(txtChave, gbc);

        // Linha 1 - Valor
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 0;
        add(lblValor, gbc);

        gbc.gridx = 1;
        gbc.weightx = 1;
        add(txtValor, gbc);

        // Linha 2 - Botão
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.gridwidth = 2;
        gbc.weightx = 0;
        gbc.insets = new Insets(15, 10, 10, 10);
        add(btnEnviar, gbc);

        btnEnviar.addActionListener(this::enviarPix);
        setVisible(true);
        
    }
    
    private void enviarPix(ActionEvent e) {
        String chave = txtChave.getText();
        String valorTexto = txtValor.getText();

        try {
            double valor = Double.parseDouble(valorTexto);
            boolean sucesso = controller.enviarPix(chave, valor);
            if (sucesso) {
                JOptionPane.showMessageDialog(this, "PIX enviado com sucesso!");
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao enviar PIX. Verifique os dados.");
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Valor inválido.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
